### ISSUE TITLE
Start a blog with a release announcement

### ISSUE THREAD

**Issue by cooperq** [ethersheet-collective/EtherSheet#12]

**Comment by JohnMcLear** [comment]
Dat 10 month window to bring up a Wordpress instance..  Let me know if you want me to bring you one up if you want to post on blog.etherpad.org :)

**Comment by cooperq** [comment]
@JohnMcLear Thanks for the offer. It turns out I actually don't have that much to blog about! I think the twitter account is probably sufficient for now.
