### ISSUE TITLE
source missing license header

### ISSUE THREAD

**Issue by KelseyBlodgett** [ethersheet-collective/EtherSheet#21]
I noticed that the JavaScript file doesn't have a license header. This seems to be a common practice amongst JavaScript libraries.
Would it be possible to add the information to the file so users can easily adhere to the project's license?
Something like:
Licensed under the MIT License
Thanks.

**Comment by JohnMcLear** [comment]
If you want it, add it.  Stallman

**Comment by cooperq** [comment]
There is a license file in the project, if somone wants to submit a PR adding license headers to the source they are welcome to do so.
