### ISSUE TITLE
SSL Certificate Expired?

### ISSUE THREAD

**Issue by madeofpeople** [ethersheet-collective/EtherSheet#30]
Hello friends,
Looks like EtherSheet.org's ssl certificate is expired?
Getting security warnings when trying to log on.

**Comment by cooperq** [comment]
It is! Sorry! I need to update it, I will try to get to it today.

**Comment by BostonEnginerd** [comment]
Looks like it's still expired.

**Comment by cooperq** [comment]
It is. I have been working on another project and at defcon. I will look at it this week. Sorry everyone!

**Comment by cooperq** [comment]
Fixed now! Sorry about the delay.
